extends: webdino-profile
overrides:
  - files: [postcss.config.js, tailwind.config.js, esbuild.*.js]
    env:
      node: true
    rules:
      "@typescript-eslint/no-var-requires": "off"
  - files: "*.tsx"
    rules:
      filenames/match-exported: ["error", "pascal"]
