name: setup
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
        cache: yarn
    - name: Restore Playwright cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-v1-main
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
    - name: Install system dependencies
      run: npx playwright install-deps
      shell: bash
    - uses: "./.github/actions/wordpress_setup"
