name: setup
description: Setup
runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v2
    - uses: actions/setup-node@v3
      with:
        node-version-file: .node-version
        cache: pnpm
    - name: Restore Playwright cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: "${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}"
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
    - name: Install browsers and system dependencies
      run: pnpm --filter @originator-profile/registry exec playwright install --with-deps
      shell: bash
    - name: Setup for WordPress plugin
      uses: "./.github/actions/wordpress_setup"
