extends: originator-profile
rules:
  # TODO: Jumpu UIがナビゲーションタブの実装に対応したら取り除いて
  # see https://github.com/tuqulore/jumpu-ui/issues/544
  jsx-a11y/no-noninteractive-element-to-interactive-role:
    - error
    - nav: ["tablist"]
  react/button-has-type: "error"
overrides:
  - files: src/components/*.tsx
    rules:
      filenames/match-exported: ["error", "pascal"]
  - files: src/pages/**/*.tsx
    rules:
      # pages/ のファイル名は generouted の規則に従うので eslint のルールは無視する
      filenames/match-exported: "off"
