name: wordpress_e2e
description: End-to-End Test for WordPress plugin
runs:
  using: composite
  steps:
    - name: E2Eテストの準備
      run: sudo apt-get install -y fonts-noto-cjk
      shell: bash
    - name: E2E tests
      run: pnpm wordpress:e2e
      shell: bash
    - name: テスト結果の保存(失敗時レポート)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-report
        path: |
          packages/wordpress/playwright-report
        retention-days: 7
