name: wordpress_setup
description: Setup for WordPress plugin
runs:
  using: composite
  steps:
    - name: Create and start containers
      run: |
        cp .env.development .env
        docker compose up -d
      shell: bash
      working-directory: packages/wordpress
    - name: Install WordPress dependencies
      run: docker compose exec -w /var/www/html/wp-content/plugins/profile wordpress composer install
      shell: bash
      working-directory: packages/wordpress
