name: e2e
description: End-to-End Test
runs:
  using: composite
  steps:
    - name: E2Eテストの準備
      run: sudo apt-get install -y fonts-noto-cjk
      shell: bash
    - name: E2E tests
      run: yarn e2e
      shell: bash
    - uses: actions/upload-artifact@v3.1.1
      with:
        path: apps/web-ext/screenshots
