name: e2e
description: End-to-End Test
inputs:
  BASIC_AUTH:
    description: レジストリ API の Basic 認証
    required: false
    default: "true"
  BASIC_AUTH_CREDENTIALS:
    description: レジストリ API の Basic 認証情報 (JSON 文字列)
    required: true
  REGISTRY_OPS:
    description: Originator Profile Set
    required: true
runs:
  using: composite
  steps:
    - name: E2Eテストの準備
      run: sudo apt-get install -y fonts-noto-cjk
      shell: bash
    - name: E2E tests
      run: pnpm e2e
      shell: bash
      env:
        BASIC_AUTH: ${{ inputs.BASIC_AUTH }}
        BASIC_AUTH_CREDENTIALS: ${{ inputs.BASIC_AUTH_CREDENTIALS }}
        REGISTRY_OPS: ${{ inputs.REGISTRY_OPS }}
    - name: テスト結果の保存(失敗時レポート)
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: e2e-report
        path: |
          packages/verify/playwright-report
          apps/web-ext/playwright-report
          apps/web-ext/screenshots
        retention-days: 7
